apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bkuo2cmp9-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-31da90664d.btmz.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:6f4b514dd3e72047ee3ef79d6b22c08cfb997bc9@sha256:b111cf5a354aca47c18681d1ffcb4f5c5ce3bef499bc42d86b3648797e98fa60
          name: container-image
